name: fastapi_test

services:

  fastapi_server:
    build:
      context: /home/cc/StudyBot-Audio-Captioning-and-Q-A-chatbot-/FastAPI_TF 
      dockerfile: Dockerfile
    container_name: fastapi_server
   # deploy:
     # resources:
       # reservations:
         # devices:
           # - driver: nvidia
             # count: all
              #capabilities: [gpu]
    ports:
      - "8000:8000"
    restart: always

  flask:
    build:
      context: /home/cc/StudyBot-Audio-Captioning-and-Q-A-chatbot-/Flask_App
      dockerfile: Dockerfile
    container_name: flask
    ports:
      - "80:5000"
    environment:
      - FASTAPI_SERVER_URL=http://fastapi_server:8000
    depends_on:
      - fastapi_server
    restart: always

  jupyter:
    image: quay.io/jupyter/minimal-notebook:latest
    container_name: jupyter
    ports:
      - "8888:8888"
    volumes:
      - /home/cc/serve-system-chi/workspace:/home/jovyan/work
    command: >
      bash -c "python3 -m pip install numpy && start-notebook.sh"
    restart: always
