version: '3.8'

volumes:
  audio_data:

services:
  extract-data:
    container_name: etl_extract_data
    image: python:3.11
    user: root
    volumes:
      - audio_data:/data
    working_dir: /data
    command:
      - bash
      - -c
      - |
        set -e

        echo "Resetting dataset directory..."
        rm -rf nptel_dataset
        mkdir -p nptel_dataset
        cd nptel_dataset

        echo "Downloading dataset ZIP from Hugging Face..."
        curl -L https://huggingface.co/datasets/nehapatil08/nptel-dataset/resolve/main/nptelfinal.zip -o nptelfinal.zip

        echo "Extracting ZIP..."
        apt update && apt install -y unzip
        unzip nptelfinal.zip
        rm -f nptelfinal.zip

        echo "Listing extracted folders..."
        ls -lh

  transform-data:
    container_name: etl_transform_data
    image: python:3.11
    volumes:
      - /home/cc/StudyBot-Audio-Captioning-and-Q-A-chatbot-/data-persist-chi:/mnt/data
      - ./pair_files.py:/pair_files.py
    working_dir: /mnt/data/nptel_dataset/nptelfinal
    command:
      - bash
      - -c
      - |
        set -e
        echo "Running pairing script..."
        python3 /pair_files.py
        echo "✅ Done. Listing paired files:"
        ls -lh /mnt/data/paired

  load-data:
    container_name: etl_load_data
    image: rclone/rclone:latest
    volumes:
      - audio_data:/data
      - ~/.config/rclone/rclone.conf:/root/.config/rclone/rclone.conf:ro
    entrypoint: /bin/sh
    command:
      - -c
      - |
        if [ -z "$RCLONE_CONTAINER" ]; then
          echo "ERROR: RCLONE_CONTAINER is not set"
          exit 1
        fi

        #echo "Cleaning up existing contents of container..."
        #rclone delete chi_tacc:$RCLONE_CONTAINER --rmdirs || true
        
        echo "Uploading paired audio files..."
        rclone copy /data/nptel_dataset/paired chi_tacc:$RCLONE_CONTAINER/paired \
          --progress \
          --transfers=32 \
          --checkers=16 \
          --multi-thread-streams=4 \
          --fast-list

        echo "Verifying upload..."
        rclone lsd chi_tacc:$RCLONE_CONTAINER
