version: '3.8'

volumes:
  audio_data:

services:
  extract-data:
    container_name: etl_extract_data
    image: python:3.11
    user: root
    volumes:
      - audio_data:/data
    working_dir: /data
    command:
      - bash
      - -c
      - |
        set -e

        echo "Resetting dataset directory..."
        rm -rf nptel_dataset
        mkdir -p nptel_dataset
        cd nptel_dataset

        echo "Downloading dataset..."
        curl -L https://github.com/AI4Bharat/NPTEL2020-Indian-English-Speech-Dataset/releases/download/v0.1/nptel-pure-set.tar.gz \
          -o nptel-pure-set.tar.gz

        echo "Extracting dataset..."
        tar -xvzf nptel-pure-set.tar.gz
        rm -f nptel-pure-set.tar.gz

        echo "Listing contents of /data after extract stage:"
        ls -lh /data/nptel_dataset

  transform-data:
    container_name: etl_transform_data
    image: python:3.11
    volumes:
      - audio_data:/data
      - ./pair_files.py:/pair_files.py  # Mount the Python script
    working_dir: /data/nptel_dataset/nptel-pure  # Go directly into wav/corrected_txt folder parent
    command:
      - bash
      - -c
      - |
        set -e
        echo "Running pairing script..."
        python3 /pair_files.py
        echo "Done. Listing paired files:"
        ls -lh paired

  load-data:
    container_name: etl_load_data
    image: rclone/rclone:latest
    volumes:
      - audio_data:/data
      - ~/.config/rclone/rclone.conf:/root/.config/rclone/rclone.conf:ro
    entrypoint: /bin/sh
    command:
      - -c
      - |
        if [ -z "$RCLONE_CONTAINER" ]; then
          echo "ERROR: RCLONE_CONTAINER is not set"
          exit 1
        fi

        echo "Cleaning up existing contents of container..."
        rclone delete chi_tacc:$RCLONE_CONTAINER --rmdirs || true

        echo "Uploading paired audio files..."
        rclone copy /data/nptel_dataset/nptel-pure/paired chi_tacc:$RCLONE_CONTAINER/paired \
          --progress \
          --transfers=32 \
          --checkers=16 \
          --multi-thread-streams=4 \
          --fast-list

        echo "Verifying upload..."
        rclone lsd chi_tacc:$RCLONE_CONTAINER



